#-------------------------------------------------------
# NAME
#-------------------------------------------------------
#
# Although not directly used by the framework, the
# application name can appear in various areas such
# as the HTML title tag or email templates.
#

name: '%env:APP_NAME%'

#-------------------------------------------------------
# URL
#-------------------------------------------------------
#
# The base URL is used for generating absolute URLs.
# Typically, it's set to the root domain such as
# 'https://example.com'.
#

url: '%env:APP_URL%'

#-------------------------------------------------------
# ENVIRONMENT
#-------------------------------------------------------
#
# Defines the environment the app is running in,
# like 'development', 'testing', or 'production'.
# Useful for loading environment-specific configurations.
#

env: '%env:APP_ENV%'

#-------------------------------------------------------
# DEBUG MODE
#-------------------------------------------------------
#
# Enables or disables debug mode. When 'true', it
# displays detailed error messages. Set it to 'false'
# in production to avoid exposing sensitive information.
#

debug: '%env:APP_DEBUG%'

#-------------------------------------------------------
# DEBUG BLACKLIST
#-------------------------------------------------------
#
# Specifies environment variables to hide from
# debug output to prevent sensitive data leaks.
# Applies to _ENV, _SERVER and request input data.
#

debug_blacklist:
    _ENV:
        - APP_KEY
    _SERVER:
        - APP_KEY

#-------------------------------------------------------
# TIMEZONE
#-------------------------------------------------------
#
# Sets the default timezone for the application.
# Defaults to 'UTC', but can be changed to match
# your local region or business requirements.
#

timezone: '%env:APP_TIMEZONE%'

#-------------------------------------------------------
# CHARSET
#-------------------------------------------------------
#
# Specifies the character encoding used by the
# application. 'UTF-8' is recommended, supporting most
# global characters and symbols reliably.
#

charset: '%env:APP_CHARSET%'

#-------------------------------------------------------
# ENCRYPTION KEY
#-------------------------------------------------------
#
# Defines the encryption settings used throughout
# the application to secure sensitive data. This
# includes, but is not limited to, sessions and cookies.
#
# The key must be kept secret and should never be
# committed to version control, It is stored in the
# .env filed and referenced here. The default cipher
# is 'AES-256-CBC', through 'AES-128-CBC' is also supported.
#

encryption:
    key: '%env:APP_KEY%'
    cipher: '%env:APP_CIPHER%'
