#-------------------------------------------------------
# DEFAULTS
#-------------------------------------------------------
# This section establishes the core settings of your
# application. It includes the application's name, URL,
# operating environment, and debug mode. Additional
# settings like timezone and character set are also
# specified here.

name: '%env:APP_NAME%'
url: '%env:APP_URL%'
env: '%env:APP_ENV%'
debug: '%env:APP_DEBUG%'
debug_blacklist: [ ]
timezone: UTC
charset: UTF-8

#-------------------------------------------------------
# ENCRYPTION
#-------------------------------------------------------
# Essential for securing session and cookie data, this
# section defines the encryption parameters. For security
# reasons, you should never save the encryption key in
# your version control software. Therefore, the key is
# defined in the .env file and referenced here.
# The default encryption cipher used is AES-256-CBC.

encryption:
    key: '%env:APP_KEY%'
    cipher: AES-256-CBC

#-------------------------------------------------------
# SERVICE PROVIDERS
#-------------------------------------------------------
# Enhance your application with additional functionality
# by configuring service providers here. The path to the
# service providers directory is defined, enabling
# automatic registration of all included providers.
# Exclude specific providers using the 'providers_ignore'
# option.

services:
    providers: '%path:app%/Providers'
    providers_ignore: [ ]

#-------------------------------------------------------
# CONSOLE COMMANDS
#-------------------------------------------------------
# Configure additional console commands for your
# application in this section. A directory path for
# storing these commands is specified, with an option
# to ignore certain commands as needed.

console:
    commands: '%path:app%/Commands'
    commands_ignore: [ ]

#-------------------------------------------------------
# ROUTING
#-------------------------------------------------------
# This section is dedicated to the application's routing
# configuration. Define paths for controllers and global
# middleware. Exclude certain global middleware using
# 'middleware_ignore'. Route patterns can also be
# configured here for consistent URL structuring.

routing:
    controllers: '%path:app%/Controllers'
    middleware: '%path:app%/Middleware'
    middleware_ignore: [ ]
    patterns:
        slug: '[a-z0-9-]+'

#-------------------------------------------------------
# SESSION AND COOKIES
#-------------------------------------------------------
# Configure session and cookie settings here.
# Pre-configurations are provided for immediate use,
# including session name, expiration, encryption, and
# handling.

session:
    name: '%env:APP_NAME%_session'
    expire: 120
    encrypt: true
    default_handler: file
    handlers:
        file:
            path: '%path:storage%/sessions'
    cookie:
        path: /
        domain: '%env:APP_URL%'
        secure: true
        http_only: true
        raw: false
        same_site: strict

#-------------------------------------------------------
# LOGGING
#-------------------------------------------------------
# Keep track of application activities with integrated
# logging. Configure logging channels and specify
# exceptions that should be excluded from logging here.

logging:
    default_channel: app
    channels:
        app:
            handlers:
                rotate:
                    directory: '%path:storage%/logs'
                    interval: day
    ignore:
        - Zaphyr\Framework\Contracts\Http\Exceptions\HttpExceptionInterface
        - Zaphyr\Router\Exceptions\MethodNotAllowedException
        - Zaphyr\Router\Exceptions\NotFoundException
